version: '3.8'

services:
  # Backend API
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: plex-request-backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    volumes:
      - ./data:/app/data
      - ./backend/plex-requests.db:/app/plex-requests.db
    networks:
      - plex-network

  # Frontend (using nginx)
  frontend:
    image: nginx:alpine
    container_name: plex-request-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./build:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
    networks:
      - plex-network

networks:
  plex-network:
    driver: bridge

volumes:
  data:
